language: scala

scala:
  - 2.10.4

jdk:
  - openjdk6

script:
  - sbt -J-Xms1024M -J-Xmx3072M $TASKS

env:
  - TASKS=test
  - TASKS=integrationTests
  - TASKS=offlineTests

notifications:
  email:
    - activator@typesafe.com
  flowdock: 394be381de623fe7bee543e905ac3320
