language: scala

scala:
  - 2.10.3

jdk:
  - openjdk6

script:
  - sbt $TASKS

env:
  - TASKS=test
  - TASKS=integrationTests
  - TASKS=offlineTests

notifications:
  email:
    - activator@typesafe.com
  flowdock: 2eb8fdbb08ad2e595a21edea64252a22
            
