language: scala

scala:
  - 2.10.3

jdk:
  - openjdk6

script:
  - sbt $TASKS

env:
  - TASKS=test SBT_OPTS="-XX:PermSize=256M -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled -XX:+UseCodeCacheFlushing -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+DoEscapeAnalysis"
  - TASKS=integrationTests SBT_OPTS="-XX:PermSize=256M -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled -XX:+UseCodeCacheFlushing -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+DoEscapeAnalysis"
  - TASKS=offlineTests SBT_OPTS="-XX:PermSize=256M -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled -XX:+UseCodeCacheFlushing -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+DoEscapeAnalysis"

notifications:
  email:
    - activator@typesafe.com
  flowdock: 394be381de623fe7bee543e905ac3320
